### ISSUE TITLE
Add new icon

### ISSUE THREAD

**Issue by SalvadorD75** [MinecraftMachina/multimc-macos-arm64#12]
sorry for putting this as an issue but I don't know how to pull a request, so the thing was that I have been using manymc and its awesome but its icon does not fit with the perfectly rounded icons every macOS integrated app has, so, if it is possible, make the icon with like white circular background and the mamymc icon inside it like the image below
![Manymc svg](https://user-images.githubusercontent.com/78454573/147797420-115d02e1-190a-459d-820d-b0cace6da29a.png)

**Comment by ViRb3** [comment]
Hey there. We have an awesome new icon in the works already, it just needs some final refinements. It will be added soon.

**Comment by SalvadorD75** [comment]
and it will have the rounded curves and all that?

**Comment by ViRb3** [comment]
Yes, it will be a proper icon by all macOS standards :)

**Comment by SalvadorD75** [comment]
nice
