### ISSUE TITLE
Type "↑" (up key) cause crash.

### ISSUE THREAD

**Issue by sawyerfeng** [MinecraftMachina/multimc-macos-arm64#15]
Excellent Job. MC with forge work well  on my machine. It really helps me a lot . 
When I type the letter  "↑" (up key)，the game crashed, whether server or local. The crash-report is as follow, hope that you can fixed it ,or help me to find out why. Thanks!
MC version 1.16.5, forge; Java version 8 or 11, all by zulu jdk.
[crash-2022-01-15_18.14.57-client.txt](https://github.com/MinecraftMachina/ManyMC/files/7874789/crash-2022-01-15_18.14.57-client.txt)
.

**Comment by ViRb3** [comment]
This is caused by the following mod: https://github.com/Windmill-City/IngameIME-Minecraft

You need to tell the developer to include an arm64 version of the native library for Mac. Alternatively, you can remove the mod.

**Comment by sawyerfeng** [comment]
!! What a fool question. Thank you for your patient reply in such a short time .

**Comment by ViRb3** [comment]
I left a note to the developer as linked above.
