### ISSUE TITLE
Doesn't work with some modpacks like Valhelsia Enhanced Vanilla

### ISSUE THREAD

**Issue by aradabir007** [MinecraftMachina/multimc-macos-arm64#16]
Hi, there seems to be some issues with some mods that I cannot pinpoint which but I'll leave the log file below.

https://paste.ee/p/GhGhq

**Comment by ViRb3** [comment]
Simple RPC Discord mod uses a native library which has not been built for M1 (arm64) Macs. Remove the mod and it will work.
