### ISSUE TITLE
won't let me launch. says I don't have java 17

### ISSUE THREAD

**Issue by Igloocooler52** [MinecraftMachina/multimc-macos-arm64#18]
every time I try to launch I get this 
> Minecraft 1.18 Pre Release 2 and above require the use of Java 17

I'm fairly sure I have java 17, so idk what to think of this

**Comment by ViRb3** [comment]
I just tried 1.18-pre2 and it works fine. A couple of things:
- Make sure that you are actually using Java 17 for ManyMC, merely having it installed is not enough. Check that in the ManyMC global Java settings, as well as in the instance Java settings, when you click the green checkbox or "Test" button, it says:
    > Java version reported: 17.0.1
- Where do you get this error? Please post full logs.

**Comment by Igloocooler52** [comment]
Java version reported: 1.8.0_311

also, sorry, idk exactly how to upload full logs. where do I go exactly?

**Comment by ViRb3** [comment]
That's Java 8. Change it to 17 and it will work.

**Comment by Igloocooler52** [comment]
might be a dumb question, but how do i make sure it runs through java 17? i
already have it installed i just dont know where to go from there

**Comment by ViRb3** [comment]
I'd suggest asking for such help in the Discord. Invite is in the README.
