### ISSUE TITLE
Microsoft game pass

### ISSUE THREAD

**Issue by recsdj** [MinecraftMachina/multimc-macos-arm64#19]
Hello,
I'm trying to run ManyMC on M1 MBP and I'm using new Microsoft account with Game pass, which supposedely includes MC Java in it. ManyMC however says "The account does not own Minecraft. You need to purchase the game first to play it". 

I googled and seems like this issue has been fixed in MultiMC already: 
https://github.com/MultiMC/Launcher/issues/4217

Is it possible to pull that request here as well? Cheers.

**Comment by recsdj** [comment]
Answering myself: after 2 days of trying different ways to "activate" my already purchased Game Pass, the final solution was to open Windows 10 on a **PC** (not in Parallels or other emulator!) and run Xbox -> Minecraft from there. This let me create MC username connected to my newly created Microsoft account and finally I can play MC Java everywhere. 

None of emulators, MC launchers (official and 3rd party), Xbox apps let me even start MC not in Demo mode -- some cryptic error messages such as 0x0000001 or "Something bad happened". Basically turns out, if you do not own an actual real PC and create a new MS account, there's no way you can play Minecraft on Mac, because you need REAL PC to activate your Minecraft account first. It won't run on MacOS no matter how you package it without such activation. Mojang and MS are real morons to act like this to their new users.

**Comment by ViRb3** [comment]
Glad you got it sorted. All account changes to date have been pulled into ManyMC from MultiMC. I'm not very sure about all the account requirements and specifics, but the behavior you're seeing here likely matches that of MultiMC.
