### ISSUE TITLE
OptiFine will not install

### ISSUE THREAD

**Issue by federicochiesa** [MinecraftMachina/multimc-macos-arm64#2]
I tried to install OptiFine on 1.18 by clicking "Add to minecraft.jar" the "OptiFine_1.18_HD_U_H3_pre6_MOD.jar" file into the Version tab
![Screen Shot 2021-12-04 at 15 21 42](https://user-images.githubusercontent.com/38504010/144712960-80c11300-dca4-4fb6-bf1c-b6af6f7a60c9.png)
.
If I launch Minecraft it shows up as modded, but OptiFine doesn't load for some reason.

**Comment by ViRb3** [comment]
You need to install Fabric and then OptiFabric. That will load your OptiFine properly.
