### ISSUE TITLE
No sound for minecraft versions that use LWJGL 2

### ISSUE THREAD

**Issue by MartinTintin3** [MinecraftMachina/multimc-macos-arm64#21]
I noticed that whenever I use minecraft versions that use LWJGL 2 not 3(Like 1.8 and 1.12), there is no sound. This isn't specific to ManyMC(This is happening on Lunar Client too), but I thought that this was the only suitable place where people talk about these kinds of things.
I think this is an issue OpenAL, not sure though

**Comment by ViRb3** [comment]
Minecraft 1.8.9 uses LWJGL2, while 1.12 uses LWJGL3. I have sound with both versions. Can you post your instance logs here? This is likely an issue with your specific setup (external sound device, some app, etc.)

**Comment by MartinTintin3** [comment]
https://pastebin.com/raw/swR8RZpk

**Comment by ViRb3** [comment]
Have you tried creating a new instance and running it completely vanilla, without any mods? I don't see anything interesting in your logs, sadly.

**Comment by MartinTintin3** [comment]
Yep, still doesn't work. Maybe it has something to do with the version of Java 8 im using(Azul Zulu). This is the only error that appears for the completely vanilla instance:
```
[22:02:25] [Client thread/ERROR]: Error while loading the narrator : java.lang.UnsatisfiedLinkError: /private/var/folders/g8/hsy5g3915r51l4jr4jgvb_h00000gn/T/jna--1224898674/jna447012736680771236.tmp: dlopen(/private/var/folders/g8/hsy5g3915r51l4jr4jgvb_h00000gn/T/jna--1224898674/jna447012736680771236.tmp, 0x0001): tried: '/private/var/folders/g8/hsy5g3915r51l4jr4jgvb_h00000gn/T/jna--1224898674/jna447012736680771236.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna447012736680771236.tmp' (no such file)
```

**Comment by ViRb3** [comment]
Can you retry using the latest version of ManyMC? There have been a few updates that may hopefully address this.

**Comment by MartinTintin3** [comment]
OMG THANK YOU!! yes it finally works

**Comment by MartinTintin3** [comment]
@ViRb3 wait can you show the commits that actually fixed this? I want to see what was the issue

**Comment by ViRb3** [comment]
I don't have a specific fix, but I re-built the latest version of OpenAL, which was updated 5 days ago :) Here's the build that ManyMC uses: https://github.com/MinecraftMachina/openal-soft

**Comment by MartinTintin3** [comment]
alright thanks
