### ISSUE TITLE
Homebrew Install

### ISSUE THREAD

**Issue by caitlynrw** [MinecraftMachina/multimc-macos-arm64#22]
Similar to mainstream MultiMC, could this application be packaged as a Homebrew Cask for streamlined installation?

**Comment by MattElek** [comment]
It seems like this has just been added to homebrew casks, see [here](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/manymc.rb).

**Comment by ViRb3** [comment]
That's great! Thank you community :)
