### ISSUE TITLE
XBox user authentication failed.

### ISSUE THREAD

**Issue by FabioBassi** [MinecraftMachina/multimc-macos-arm64#25]
I am not able to log in to my Microsoft account. I follow the instructions on screen and I verify my account in the browser tab, but when I come back to the program I find the message "XBox user authentication failed."
I've tried to reinstall ManyMC but the issue persists; I hope I'm doing something wrong.
![Schermata 2022-02-10 alle 16 26 50](https://user-images.githubusercontent.com/68322801/153439940-d133e020-c345-4899-aced-57fa086c22d1.png)

**Comment by ViRb3** [comment]
Try playing at least once using [the official launcher](https://www.minecraft.net/en-us/download) so that your account gets set up. Join a multiplayer server like `mc.hypixel.net` to ensure it works. Then try ManyMC again.

**Comment by FabioBassi** [comment]
Thank you for your quick reply!
Unfortunately the trick didn't work. With the official launcher I've got no problems logging in and playing on a multiplayer server.
I even tried using different browsers.

**Comment by ViRb3** [comment]
I see. Upon a quick look, seems like this is the same as:
```
https://github.com/MultiMC/Launcher/issues/4503
```
Try the workaround there and see if that helps. Do not ask in that issue for support of ManyMC though. Seems like this is an issue on Microsoft's side and ManyMC/MultiMC's error handling is not great.

**Comment by FabioBassi** [comment]
What listed in the MultiMC issue that you mentioned did not work (even though the two issues seam related), but I finally managed to log in by first creating an instance (1.18.1) of the game and then trying to log in!

**Comment by ViRb3** [comment]
I don't think the instance is what solved it for you, but rather Microsoft's auth servers getting back to order, but glad it was resolved either way :)
