### ISSUE TITLE
Modpack Not Working at all with ManyMC

### ISSUE THREAD

**Issue by Dumbob5892** [MinecraftMachina/multimc-macos-arm64#27]
I tried launching a modpack, Botany's Blemished to be exact, and it launched fine. The problem arose when I tried to create a world. The loading screen got stuck like shown below:
(https://user-images.githubusercontent.com/99699682/153975362-49570623-ab5e-4225-8754-af9fb3945b92.png)
When I force quit java, since it wasn't responding, and then reopened it, it showed that a world was already created. (Though I hadn't created a world yet minus that failed attempt.) When i tried to load the world shown there it did the same thing, not going past 0% loaded, and the small square of colors in the center. 

Please help, I really want to be able to run this modpack this way.

**Comment by ViRb3** [comment]
Send logs please. One of the mods likely causes the crash.

**Comment by Dumbob5892** [comment]
[latest.log](https://github.com/MinecraftMachina/ManyMC/files/8065062/latest.log)
Is this the log? this is the latest log.

**Comment by ViRb3** [comment]
Yup, that's the correct log.

```
[19:58:04] [FileSystemWatcher/ERROR]: Uncaught exception in thread "FileSystemWatcher"
java.lang.OutOfMemoryError: Java heap space
[19:58:04] [FileSystemWatcher/ERROR]: Uncaught exception in thread "FileSystemWatcher"
java.lang.OutOfMemoryError: Java heap space
```

Your game ran out of RAM. Make sure you allocate at least 6GB via the ManyMC instance Java settings. Additionally, the modpack comes with a shader pack that does not support M1 Macs. Disable it.

I downloaded the same modpack, gave it 6GB RAM and disabled the shader pack via ManyMC instance settings, and the world generates perfectly. Plays very smoothly too :)
