### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Priultimus** [MinecraftMachina/multimc-macos-arm64#3]
While the workaround listed allows me to *re-open* Minecraft, I am presently unsure of exactly how to get it to function in full screen? Is that just not supported? And if so, are there plans to support fullscreen? It feels like a pretty integral part of the game IMO.

**Comment by ViRb3** [comment]
I haven't really looked into it since I always play with maximized window. I like being able to Cmd+Tab at will. What benefit does fullscreen have?

**Comment by Priultimus** [comment]
Maximizing window...isn't full screen? Forgive me if that's a dumb question, I'm new to using a Mac haha

**Comment by Priultimus** [comment]
Oh! The green button works exactly the same as full screen awesome. Okay. I didn't know that'd work, when I had tried it before it left a strange black bar at the top but now it seems to function fine, sorry for the silly question!

**Comment by ViRb3** [comment]
No worries at all! I should probably document this workaround in the known issues section. You can also double-click on the title of the Minecraft window to maximize it without going into a separate desktop. That's what I prefer.

**Comment by dcamenisch** [comment]
Is there a possibility to disable / set the fullscreen option to false in the config automatically? Since some modpackt ship with a config that enables fullscreen by default.

**Comment by ViRb3** [comment]
Automatically? No. The manual setup in the known issues section is the best way at the moment.
