### ISSUE TITLE
Fullscreen mode broken in 1.12.2

### ISSUE THREAD

**Issue by PrimePlatypus** [MinecraftMachina/multimc-macos-arm64#30]
When I try to go into fullscreen mode in 1.12.2, instead of going into fullscreen mode normally it uses 1/4 of the screen and snaps to the bottom left corner, and the rest of the screen unused. I do have liteloader with no mods installed, but I can confirm that it also happens in vanilla. Works normally in 1.18.1. Screenshot attached below.
<img width="1440" alt="Screen Shot 2022-02-15 at 9 17 53 PM" src="https://user-images.githubusercontent.com/53546967/154183861-821feaf2-5edd-42e5-9f79-6dace2d16b97.png">
.

**Comment by ViRb3** [comment]
Unfortunately this is a known bug. I recommend expanding the game window instead of playing fullscreen for now.

**Comment by ViRb3** [comment]
Could be related to #36

**Comment by ViRb3** [comment]
This has been fixed in https://github.com/MinecraftMachina/lwjgl/releases/tag/2.9.4-20150209-mmachina.2. Simply restart ManyMC and you will get the update.
