### ISSUE TITLE
Fullscreen mode does not change screen resolution

### ISSUE THREAD

**Issue by MagOO33** [MinecraftMachina/multimc-macos-arm64#32]
Hello,
I've recently found that changing the fullscreen resolution of the game in graphical options does change the calculated resolution but not the screen resolution.
For me, this signify that my screen resolution always remind 4K but the game resolution is calculated as defined.
The problem is that lowering the game resolution does not give the graphical boost it should give.
The game is always upscaled at 4K.
Seems to be the same process than in MacOS desktop resolutions.
I have a M1 Mac mini running 12.2.1 and java17.0.2 on Minecraft 1.18.1

**Comment by ViRb3** [comment]
> does change the calculated resolution but not the screen resolution

What do you mean by that? The full screen resolution will change the rendering resolution, i.e., the amount of detail your video card has to put out (calculate). Reducing this will definitely improve performance, but not by much (read ahead).

> The game is always upscaled at 4K.

Yes, the game will always fill your whole screen when in full screen mode, this is by definition. However, if your rendering resolution is lower than your screen resolution, the details will be "stretched", retaining the "low" rendering quality. Your video card will not be doing more work. This will still yield performance improvements.

> The problem is that lowering the game resolution does not give the graphical boost it should give.

I just tested with full screen @ 2k and full screen @ lowest resolution, and I can confirm there is a FPS improvement of about 30 (on M1 Max). However this is a best case scenario, and if you are loading a lot of chunks or there are a lot of particles, this difference will become much lower.

All in all, the M1 chip on the Mac Mini has its limits. It doesn't help that Minecraft is not yet optimized for arm chips like the M1. Some more time will be necessary to match the performance on Windows, especially with 4K displays.

**Comment by MagOO33** [comment]
What I mean is this : if I choose a HD resolution in game, my screen should display a HD resolution.
It's not the case because the graphic part of the M1 upscales it at 4K whatever the resolution I choose in game.
That is not good because graphic buffers are still used in 4K.

**Comment by ViRb3** [comment]
I'm not sure I understand the problem. If you have Minecraft running full screen, it will inevitably always cover the full screen. If you have selected a low resolution, the image will be stretched. If you have selected native resolution, it will be rendered as-is. Stretching is not a GPU intensive operation, so it will have better performance than native resolution. Everything here is working properly and by design.
