### ISSUE TITLE
Cannot join Sky Factory 4 server due to missing mods

### ISSUE THREAD

**Issue by alex1651** [MinecraftMachina/multimc-macos-arm64#34]
I have an issue with Sky Factory 4 on both CurseForge and ATlauncher. I am using forge 14.23.5.2860 and running MineCraft 1.12.2. When I click launch and then go to Multiplayer, the server is listed and shows users connected, but when I click join. I get a message "Failed to connect to the server This server has mods that require FML/Forge to be installed on the client. Contact your server admin for more details." The Sky Factory 4 install is a brand new SF4 install. 

I am using an M1 Mac on Mac OS Monterey.

**Comment by ViRb3** [comment]
Did you actually install the modpack? When you go into single player, do you see any modded items? The easiest way to install a modpack is by selecting it from the CurseForge tab while creating a new instance in ManyMC. If that's not the problem, your server likely has extra mods that are not present in your modpack. You'll need to ask the server owner for those and install them separately.

**Comment by alex1651** [comment]
ViRb3,

I tried starting the mudpack in single player by creating a new world and a normal Minecraft world loads up. I tried to install Sky Factory 4 from the "Add Instance" button and trying both CurseForge and ATLauncher. When I edit the instance, on the version tab. I see LWJGL 2 first, then Forge version 14.23.5.2860 and then Minecraft 1.12.2. If I click Loader Mods, I see a full list of mods, that are in Sky Factory 4.

I am running version 0.0.7-custom
Platform: macOS-arm64
Channel:custom

**Comment by ViRb3** [comment]
> a normal Minecraft world loads up

So, non-modded? This definitely means something is wrong.

I just tested the same modpack as you and it works flawlessly.

Try resetting your ManyMC settings:
1. Fully exit ManyMC
2. Delete the data:
    ```
    ~/Library/Application Support/ManyMC
    ```
3. Retry the modpack
