### ISSUE TITLE
Minecraft below 1.13 crashes with Java 8 installed 

### ISSUE THREAD

**Issue by PabloThi** [MinecraftMachina/multimc-macos-arm64#37]
Hey there, 

first off, thank you a lot for your work!

I'm getting this error message with all Versions below 1.13. Do you think you could help me resolve this? 

ManyMC version: 0.0.7-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.66.119.69]

session.minecraft.net resolves to:
    [3.211.39.224, 52.205.99.166, 3.224.239.34]

textures.minecraft.net resolves to:
    [18.66.112.77, 18.66.112.103, 18.66.112.79, 18.66.112.60]

api.mojang.com resolves to:
    [108.138.21.89]

Minecraft folder is:
/Users/pablo/Library/Application Support/ManyMC/instances/1.7.10/.minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 1.8.0_322, using aarch64 architecture, from Azul Systems, Inc..

Main Class:
  net.minecraft.client.main.Main

Native path:
  /Users/pablo/Library/Application Support/ManyMC/instances/1.7.10/natives

Libraries:
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/ca/weblite/java-objc-bridge/1.1.0-mmachina/java-objc-bridge-1.1.0-mmachina.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/google/guava/guava/15.0/guava-15.0.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  /Users/pablo/Library/Application Support/ManyMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209-mmachina/lwjgl-platform-2.9.4-nightly-20150209-mmachina-natives-osx.jar
  /Users/pablo/Library/Application Support/ManyMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-osx.jar

Params:
  --username  --version MultiMC5 --gameDir /Users/pablo/Library/Application Support/ManyMC/instances/1.7.10/.minecraft --assetsDir /Users/pablo/Library/Application Support/ManyMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="ManyMC: 1.7.10", -Xms163m, -Xmx16384m, -Duser.language=en]

Minecraft process ID: 18171

Using onesix launcher.

[12:55:09] [main/INFO]: Setting user: Thranduillion
[12:55:09] [main/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[12:55:09] [Client thread/INFO]: LWJGL Version: 2.9.4
Process crashed with exitcode 5.
Clipboard copy at: 14 Mar 2022 12:55:11 +0100

**Comment by ViRb3** [comment]
Apologies, I accidentally broke 1.12 and below yesterday. I pushed a fix to the meta repo, and it should start working for you within 15 minutes. Please let me know if that is not the case.

**Comment by PabloThi** [comment]
Thank you for your answer. I'm not sure I understand what I have to do. Very sorry, I'm not really gifted in the usage of github. What is a meta repo and what do I do to install the fix?

**Comment by ViRb3** [comment]
All you need to do is restart ManyMC and try to start your instance again. It will pull all updates automatically :)
