### ISSUE TITLE
Add support for Forge 1.17+

### ISSUE THREAD

**Issue by jclendineng** [MinecraftMachina/multimc-macos-arm64#4]
Forge 1.18 was just released, can support be added? Thank you!

**Comment by ViRb3** [comment]
Forge above 1.16 is currently not supported due to compatibility issues inherited from MultiMC. Hopefully MultiMC will be updated soon and I will be able to add support as well.

**Comment by ViRb3** [comment]
Well, it looks like it is early Christmas - Forge for Minecraft 1.17 and above has been added. Make sure you are on Build 3 of ManyMC.
