### ISSUE TITLE
1.12.2 only using quarter window after LWJGL update

### ISSUE THREAD

**Issue by dustinlieu** [MinecraftMachina/multimc-macos-arm64#40]
Minecraft 1.12.2 is only using the bottom left quarter of the window after updating to macOS 12.3. It was fine before updating macOS. On the latest 1.18.2 update with Java 17 it's normal.

Computer details:
- MacBook Pro 14 inch 2021
- macOS 12.3
- zulu8.60.0.21-ca-jdk8.0.322-macosx_aarch64
- Vanilla Minecraft 1.12.2
- ManyMC build 7

~~EDIT: I'm not sure if this is related to the macOS update or the LWJGL update.~~
EDIT 2: It's due to the LWJGL update, not the macOS update. See comment below.

<img width="966" alt="Screen Shot 2022-03-16 at 11 12 46 PM" src="https://user-images.githubusercontent.com/18184165/158747971-13759670-ee45-4769-b872-d7f3c2494b9e.png">

**Comment by dustinlieu** [comment]
Reverting the LWJGL update in [ce15fada7a](https://github.com/MinecraftMachina/meta-multimc-arm64/commit/ce15fada7a07c1345e8e8dd081d7268d128b58f6) fixes it.

Old, but working:
```
"sha1": "70c455878ef3281f3f2aea125bec69c78cda1ff6",
"size": 469386,
"url": "https://minecraftmachina.github.io/minecraft-arm64-patches/lwjgl-2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-osx.jar"
```

**Comment by ViRb3** [comment]
I can confirm the bug, I have temporarily reverted to the old LWJGL2 build and will keep  this open until I fix it in my build.

**Comment by ViRb3** [comment]
This has been fixed in https://github.com/MinecraftMachina/lwjgl/releases/tag/2.9.4-20150209-mmachina.2. Simply restart ManyMC and you will get the update.
