### ISSUE TITLE
Build failing due to CMakeList errors

### ISSUE THREAD

**Issue by Hulkstern** [MinecraftMachina/multimc-macos-arm64#45]
The build script seems to find my zulu java 8 install just fine, but then throws some errors regarding CMakeLists.txt missing in two directories. Not sure if this is a general issue or if it something specific to my system. I'm not really experienced enough to say.
I've included a copy of the output below in case it helps.
[buildsh.txt](https://github.com/MinecraftMachina/ManyMC/files/8347482/buildsh.txt)

**Comment by ViRb3** [comment]
You don't have the git submodules cloned. Do that with:
```sh
git submodule update --init --recursive
```

**Comment by Hulkstern** [comment]
> You don't have the git submodules cloned. Do that with:
> 
> ```shell
> git submodule update --init --recursive
> ```

Perfect that solved my problem, thank you!
