### ISSUE TITLE
Pixelmon mudpack does not open : Error

### ISSUE THREAD

**Issue by johancedaniel** [MinecraftMachina/multimc-macos-arm64#49]
I got this error when i tried to launch the pixelmon modpack with ATL launcher, and also i was able to launch 1.18.2 with no issues. Please help

ManyMC version: 0.0.7-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.192.152.51, 54.192.152.53, 54.192.152.50, 54.192.152.49]

session.minecraft.net resolves to:
    [3.224.239.34, 3.211.39.224, 52.205.99.166]

textures.minecraft.net resolves to:
    [65.9.103.34, 65.9.103.92, 65.9.103.79, 65.9.103.8]

api.mojang.com resolves to:
    [54.192.171.51, 54.192.171.32, 54.192.171.70, 54.192.171.56]

Minecraft folder is:
/Users/johancedaniel/Library/Application Support/ManyMC/instances/Pixelmon Mod Pixelmon-8.3.8/minecraft

Java path is:
/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java

Checking Java version...
Java is version 17.0.2, using aarch64 architecture, from Azul Systems, Inc..

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /Users/johancedaniel/Library/Application Support/ManyMC/instances/Pixelmon Mod Pixelmon-8.3.8/natives

Libraries:
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/ca/weblite/java-objc-bridge/1.1.0-mmachina.1/java-objc-bridge-1.1.0-mmachina.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-universal.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209-mmachina.2/lwjgl-platform-2.9.4-nightly-20150209-mmachina.2-natives-osx.jar
  /Users/johancedaniel/Library/Application Support/ManyMC/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] BOP-Patch-1.0
  [✔️] fancymenu_1.5.2_MC_1.12-1.12.2
  [✔️] Gameshark-1.12.2-6.0.6-universal
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] konkrete_1.0.3_MC_1.12-1.12.2
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] PixelExtras-1.12.2-2.5.17-universal
  [✔️] Pixelmon-1.12.2-8.3.8-universal

Params:
  --username  --version MultiMC5 --gameDir /Users/johancedaniel/Library/Application Support/ManyMC/instances/Pixelmon Mod Pixelmon-8.3.8/minecraft --assetsDir /Users/johancedaniel/Library/Application Support/ManyMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="ManyMC: Pixelmon Mod Pixelmon-8.3.8", -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 8763

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
Exiting with -1
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Process exited with code 255.
Clipboard copy at: 28 Mar 2022 06:56:37 +0530

**Comment by r58Playz** [comment]
> - Forge crashes on boot
>    - Either update it to the latest version, or downgrade to Java build 320 or before

Check the [troubleshooting section](https://github.com/MinecraftMachina/ManyMC#troubleshooting) of the README.

**Comment by ViRb3** [comment]
First of all, this is not ATL Launcher. Second, please read the ticket template, more specifically, the part where you should check the troubleshooting section: https://github.com/MinecraftMachina/ManyMC#troubleshooting

**Comment by ViRb3** [comment]
> > * Forge crashes on boot
> >   
> >   * Either update it to the latest version, or downgrade to Java build 320 or before
> 
> Check the [troubleshooting section](https://github.com/MinecraftMachina/ManyMC#troubleshooting) of the README.

Don't think it's that, they're using Java 17 for 1.12.2 modpack :)
