### ISSUE TITLE
Optifine HD U H3 1.18 doesn't work

### ISSUE THREAD

**Issue by leonardodolc** [MinecraftMachina/multimc-macos-arm64#5]
Optifine 1.18 final version keeps crashing after loading the world.
Using the preview versions up to preview 7 "preview_OptiFine_1.18_HD_U_H3_pre7" works great but just to this version.
Crash report log: https://paste.ee/p/7PHtU

Since I'm not an expert on programming I'm not sure who to report this to, so I'm sorry if I'm at the wrong place!

**Comment by ViRb3** [comment]
This is definitely the only correct place to report, so good job on that!

Seems like something is forcing the initialization of the narrator (text-to-speech), which is known to cause a crash. I will find a way to make the narrator impossible to load and that should fix this crash. Will keep you updated.

**Comment by leonardodolc** [comment]
thank you very much!

**Comment by ViRb3** [comment]
Actually, ignore my previous statement. The issue appears to be in OptiFabric. You will simply need to wait for it to update for the latest OptiFine. Track this:
```
https://github.com/Chocohead/OptiFabric/issues/497
```

As a workaround, seems like you can disable `Fabric API` and only keep `OptiFine` and `OptiFabric`. I just tested that and it works.

**Comment by ViRb3** [comment]
Well, it looks like it is early Christmas - Forge for Minecraft 1.17 and above has been added, and OptiFine works great with that. You can use it instead of OptiFabric for now. Make sure you are on Build 3 of ManyMC.

**Comment by leonardodolc** [comment]
Just tried it and it works great, thank you for your time!
