### ISSUE TITLE
Option to sign into Microsoft Account greyed out

### ISSUE THREAD

**Issue by Hulkstern** [MinecraftMachina/multimc-macos-arm64#50]
**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

When trying to add a new account in settings, the option to add a new Microsoft account is greyed out/disabled.

**To reproduce**

1. build from latest source (For me from ba4e7a5dae3bdaf862de8c4c14414bab277091bd )
2. Move built app into Applications Directory and Launch (in my case, having installed no prior version of ManyMC)
3. Open settings > Accounts
4. Notice the option to add a Microsoft Account is not available/disabled.

**Expected behavior**

Should be able to add a Microsoft account (especially since it's recently become mandatory to use them)

**Logs**

N/A (I think)

**Screenshots**
*Observe*
<img width="1002" alt="Screen Shot 2022-03-28 at 23 25 33" src="https://user-images.githubusercontent.com/30249728/160527826-402fbb77-a9ed-47c3-9704-d42101e898ad.png">

**System configuration**

- ManyMC version: 0.6.14-custom
- Java version: Azul JDK 1.8 (1.8.0_322)

**Additional context**

N/A

**Comment by ViRb3** [comment]
Ah yes, this is normal. You need to provide a Microsoft Identity Platform client ID when building ManyMC for Microsoft integration to work. You have to register with Microsoft and obtain this key. More info here: https://github.com/MinecraftMachina/ManyMC/tree/develop/notsecrets

**Comment by Hulkstern** [comment]
> Ah yes, this is normal. You need to provide a Microsoft Identity Platform client ID when building ManyMC for Microsoft integration to work. You have to register with Microsoft and obtain this key. More info here: https://github.com/MinecraftMachina/ManyMC/tree/develop/notsecrets

This should be included in the troubleshooting guide as well, since this is a problem unique to forks of MultiMC.

**Comment by ViRb3** [comment]
Original MultiMC (and any other launcher, really) will have the exact same  problem. I will add a note in the building guide though.
