### ISSUE TITLE
add offline mode without account

### ISSUE THREAD

**Issue by zainullahk** [MinecraftMachina/multimc-macos-arm64#51]
ik it sounds dumb but  we should be able to  play the game without an account 
a lot of other launchers like sklauncher have this feature

**Comment by JJTech0130** [comment]
Playing without an account is pirating.

**Comment by zainullahk** [comment]
its not my fault i own mc pe and mc ps4 but it doesnt transfer to my pc

**Comment by ViRb3** [comment]
This is indeed piracy, and as such, will never be added. Please raise your concerns with Mojang/Microsoft.
