### ISSUE TITLE
I can't get vault hunters mudpack to run

### ISSUE THREAD

**Issue by Skywalker8510** [MinecraftMachina/multimc-macos-arm64#52]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

I installed the vault hunters modpack and tried both through curseforge and the zip file but it does the same thing both times

**To reproduce**

install vault hunters modpack and start it.

**Expected behavior**

it just runs

**Logs**

https://pastebin.com/KxhGX74C

**System configuration**

- ManyMC version: latest
- Java version: Azul JDK 17 (17.0.2)
- M1 iMac 16gb ram

**Additional context**

Add any other context about the problem here. when I tried using curseforge to launch it I had a similar problem and used the steps in this Reddit post to get the game running. https://www.reddit.com/r/VaultHuntersMinecraft/comments/so4rad/comment/hw6pqje/?utm_source=share&utm_medium=web2x&context=3

**Comment by ViRb3** [comment]
Please read the troubleshooting guide even more carefully.

Spoiler:

> **Minecraft 1.16 and before crash on boot**
To fix, install an arm64 native version of Java 8 (i.e. [Azul OpenJDK 8 arm64](https://www.azul.com/downloads/?version=java-8-lts&os=macos&architecture=arm-64-bit&package=jdk)). Set your instance in ManyMC to use this version

**Comment by Skywalker8510** [comment]
how do i set it to java 8 I already installed from that link

**Comment by Skywalker8510** [comment]
nevermind i think i figured it out

**Comment by Skywalker8510** [comment]
so i tried it with java 8 and need up having the same thing happen
https://pastebin.com/KxqjWSMA

**Comment by ViRb3** [comment]
Again, your answer is in the troubleshooting guide.

> **Forge crashes on boot**
Either update it to the latest version, or downgrade to Java build 320 or before

**Comment by Skywalker8510** [comment]
how do i downgrade to 320

**Comment by Skywalker8510** [comment]
so i don't know what changed between yesterday and today but it didn't work yesterday and it works today this modpack just hates me
