### ISSUE TITLE
Update the icon

### ISSUE THREAD

**Issue by morimoto-ltd** [MinecraftMachina/multimc-macos-arm64#53]
Apple arm64 architecture supported only on MacOS >= BigSur, so it makes sense to have an icon that uses MacOS icon guides.

I have this two variants:
![IMG_258A9CF773CE-1](https://user-images.githubusercontent.com/55985019/163679127-b26857dd-5b54-4e46-a396-edb72cfd0a91.jpeg)

I'll prepare one or both of them after approval.

_Also, pleas add a label, because I only found how to add a "bug"_

**Comment by ViRb3** [comment]
I absolutely love the icons, thanks so much. I'm more than happy to replace the current one. I'm currently on vacation, but I'll get back to you next week and get it sorted.

**Comment by d-513** [comment]
I vote for the first, just so its more recognizable as minecraft launcher.
Awesome icons btw

**Comment by ViRb3** [comment]
@morimoto-ltd I just held a vote on the community Discord, and although the votes were almost evenly split, the first one (green) wins by a bit. I also agree that the color makes it more recognizable as Minecraft, so let's go with that! So, could you please send me a vectorized version of the first (green) icon? `.svg` or vectorized `.icns` would be ideal. I will release an update as soon as you are ready with the icon. Thanks a lot!

![Screen Shot 2022-04-20 at 13 52 24](https://user-images.githubusercontent.com/2650170/164234692-e83afcd9-8c74-42cd-aff6-2aa7776530ed.png)

**Comment by lokka30** [comment]
Both look sweet as!

**Comment by MoustacheOff** [comment]
> @morimoto-ltd I just held a vote on the community Discord, and although the votes were almost evenly split, the first one (green) wins by a bit. I also agree that the color makes it more recognizable as Minecraft, so let's go with that! So, could you please send me a vectorized version of the first (green) icon? `.svg` or vectorized `.icns` would be ideal. I will release an update as soon as you are ready with the icon. Thanks a lot!
> 
> ![Screen Shot 2022-04-20 at 13 52 24](https://user-images.githubusercontent.com/2650170/164234692-e83afcd9-8c74-42cd-aff6-2aa7776530ed.png)

@ViRb3 Hey! I'm really hyped about this update. I can help if you want to make a vectorized version (as an SVG and a ICNS file) of the first icon if you can send, if possible, the cube here (or on Discord: Moustache#0001). Likewise, I have made several icons for macOS, respecting Apple's Design Guidelines.

**Comment by ViRb3** [comment]
Given that OP created these icons, I am sure that they have vectorized versions. Let's just wait for their response :)

**Comment by morimoto-ltd** [comment]
Yep, that's vector
I have not much time currently because of job, but will prepare the green version and send it by the end of the week

**Comment by ViRb3** [comment]
No rush at all. On another note, seems like the green version has officially won by a large margin:

![Screen Shot 2022-04-21 at 17 25 30](https://user-images.githubusercontent.com/2650170/164506954-f4d50f19-ac49-4919-a8fc-d3a6322e06ea.png)

**Comment by morimoto-ltd** [comment]
I've made a pixelated version with all sizes that needed + tuned each one to look better after rasterization.
Originals, svgs and icons used by iconutil are included too, just in case
[ManyMC icon.zip](https://github.com/MinecraftMachina/ManyMC/files/8535338/ManyMC.icon.zip)

**Comment by ViRb3** [comment]
Looking great! May I just ask why the smaller icons are pixelated? I'm not even sure where the smaller icons are used to be honest...

**Comment by morimoto-ltd** [comment]
You mean svgs? Idk actually
Looks like Affinity has no way to convert inner/outer shadows to svgs. Problems of proprietary formats 🤷🏽
I'll try to do something with it, but at bit later. Originals included too anyway.

If you about pngs -- I've done this for them to look good everywhere, because in small sizes shapes are looking distorted. + MacOS always puts icons right on screen's pixel grid

**Comment by morimoto-ltd** [comment]
Smaller ones used on external screens with lower resolution in finder for example 
<img width="64" alt="image" src="https://user-images.githubusercontent.com/55985019/164560496-5d43b691-9e5c-40ed-ae38-6e4d4e6c3fae.png">
And middle-sized ones are for dock mostly
<img width="82" alt="image" src="https://user-images.githubusercontent.com/55985019/164560538-c2652ad2-2399-457a-962d-3ec0e6f61941.png">

**Comment by ViRb3** [comment]
Actually, my bad. The SVGs look super pixelated because macOS Preview stretches them in a non-vectorized way. Opening them in Adobe Illustrator, they look crystal clear. Everything is looking great to me, I will release an update shortly and of course credit you. Thanks so much for this amazing icon!

**Comment by morimoto-ltd** [comment]
You're welcome!
Looking forward to contribute more after I find time to learn smth more than JS
