### ISSUE TITLE
Snapshot 22w16b (and presumably later) use LWJGL 3.3.1, causing crash due to conflict?

### ISSUE THREAD

**Issue by rinOfTheStars** [MinecraftMachina/multimc-macos-arm64#54]
**Describe the bug**

As of Minecraft Snapshot 22w16a, Mojang has upgraded the version of LWJGL Minecraft is built against to 3.3.1
Presumably due to ManyMC shipping it's own ARM64 binaries for older LWJGL versions, ManyMC seemingly fails to correctly pick a LWJGL binary to use, and the game crashes before launching.

**To reproduce**

1. Download the latest snapshot, 22w16b, via ManyMC, and attempt to launch it with a native build of Java 17.

**Expected behavior**

The game launches as normal.

**Logs**

Log 1: ManyMC Console Logs - https://paste.ee/p/8Tf73
Log 2: Latest.log file - https://paste.ee/p/S1uJC

**System configuration**

- ManyMC version: 0.0.7
- Java version: Azul JDK 17, ARM64 macOS
- macOS version: macOS 12.3.1

**Comment by ViRb3** [comment]
Hey! Many thanks for raising this. I just pushed a fix, try again in a few minutes and it should work.
