### ISSUE TITLE
fps problem (fixed)

### ISSUE THREAD

**Issue by hugokuo123** [MinecraftMachina/multimc-macos-arm64#57]
my fps is locked on 60, why?
I've turned the max framerate into unlimited.[https://img.onl/v1AZXn](url)
MantMC version:0.0.9.-1
zulu java version:zsrc17.34.19-jdk17.0.3

**Comment by JJTech0130** [comment]
Are you in fullscreen? Is VSync on? On my PC being in fullscreen locks the FPS to 60.

**Comment by JJTech0130** [comment]
Here’s the image directly attached. I had trouble getting the link to work without typing it in manually.
![238B1A05-EA47-4694-967B-B11C47EFC992](https://user-images.githubusercontent.com/53275876/166151838-648dc0fd-0949-4bb2-b291-04d5c0c9aa92.png)
