### ISSUE TITLE
What is the method to start minecraft?

### ISSUE THREAD

**Issue by ilgrandeanonimo** [MinecraftMachina/multimc-macos-arm64#58]
i want to do the same thing but with a python script (to velocize the game start), I created the authenticator but I don't now how can I start the game! can you help me? please

**Comment by ViRb3** [comment]
What do you mean?

**Comment by ilgrandeanonimo** [comment]
what is the java command to start minecraft

**Comment by ViRb3** [comment]
There isn't an easy Java command to launch Minecraft. The launcher will make a lot of decisions based on the situation. What you can do is run Minecraft through ManyMC via a command. Do `/Applications/ManyMC/Contents/MacOS/ManyMC --help`

**Comment by ilgrandeanonimo** [comment]
I actually intend to create a launcher just that to make things easier for you I preferred for you to help me just figure out how to do it. Then I would have thought about creating it all in swift. (I said in Python because it's very similar to swift)

**Comment by ViRb3** [comment]
Oh. But ManyMC already works really well, I don't think there's a need to rewrite it in any new language. You're more than welcome to try, but it's not something I can help with. The source code is at your disposal.

**Comment by ilgrandeanonimo** [comment]
Yes but I don't like the design. I wish to make a things with the macOS style. And I don't understand very much C++. 😅

**Comment by ilgrandeanonimo** [comment]
One thing, I suggest to you to change the LWJGL version and restrict it to the 3.3.0 and highest because it's the first version that is compatible with ARM64. Excuse for my bad English but I'm not English and I don't write so good English.

**Comment by JJTech0130** [comment]
> One thing, I suggest to you to change the LWJGL version and restrict it to the 3.3.0 and highest because it's the first version that is compatible with ARM64. Excuse for my bad English but I'm not English and I don't write so good English.

Pretty sure ManyMC already dealt with that. I think they backported the patches or smth.

**Comment by ViRb3** [comment]
Correct. LWJGL 3.3.0 is used everywhere.

**Comment by JJTech0130** [comment]
> There isn't an easy Java command to launch Minecraft. The launcher will make a lot of decisions based on the situation. What you can do is run Minecraft through ManyMC via a command. Do `/Applications/ManyMC/Contents/MacOS/ManyMC --help`

> Yes but I don't like the design. I wish to make a things with the macOS style. And I don't understand very much C++. 😅

I think what @ViRb3 was trying to say was that you could write a wrapper around the command line version of ManyMC. With whatever GUI you want. (i.e. using [`subprocess.Popen()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) or [Swift's `Foundation` framework](https://stackoverflow.com/a/50035059))

**Comment by ilgrandeanonimo** [comment]
Yes I now
