### ISSUE TITLE
Simple Voice Chat mod support on 1.16.5 (permissions issue)

### ISSUE THREAD

**Issue by devqcf** [MinecraftMachina/multimc-macos-arm64#6]
So on this [page](https://github.com/henkelmax/simple-voice-chat/tree/1.17.1/macos) from SVC mod creator it says the launcher needs NSMicrophoneUsageDescription in it's Info.plist and signed with microphone entitlement. For me on 1.16.5 the mod doesn't ask for microphone permission, and I can't hear anyone. 
New versions of SVC have a workaround, but on 1.16.5 the mod wasn't updated for a few months, missing permission workaround

**Comment by JJTech0130** [comment]
Try the [standalone version](https://github.com/henkelmax/simple-voice-chat/files/7652354/simple-voice-chat-macos-workaround.zip) of the workaround?

**Comment by devqcf** [comment]
> Try the [standalone version](https://github.com/henkelmax/simple-voice-chat/files/7652354/simple-voice-chat-macos-workaround.zip) of the workaround?

I don't really understand how do I use it

**Comment by devqcf** [comment]
Now I even tried to clone the repo and change its info.plist, but for some reason there is no support for Microsoft accounts when you clone

**Comment by JJTech0130** [comment]
It looks like it’s an executable .jar file, so I think you can run it by double clicking on it? If not you might have to use the terminal.

**Comment by JJTech0130** [comment]
> Now I even tried to clone the repo and change its info.plist, but for some reason there is no support for Microsoft accounts when you clone

Yeah that’s because MS account support requires a secret to be compiled into the app. See  [this file](https://github.com/MinecraftMachina/ManyMC/blob/develop/notsecrets/Secrets.cpp) for an explanation.

**Comment by devqcf** [comment]
> It looks like it’s an executable .jar file, so I think you can run it by double clicking on it? If not you might have to use the terminal.

Tried it. Terminal is showing errors, nothing happens when I double click

**Comment by JJTech0130** [comment]
Hmm… what errors? You are using `java -jar [jarname.jar]`? I don’t have an M1 Mac, so I unfortunately cannot test.

**Comment by devqcf** [comment]
> 

```
java -jar /Users/deargo/Downloads/simple-voice-chat-macos-workaround.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: de/maxhenkel/voicechat/macos/StandaloneMain has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

**Comment by devqcf** [comment]
> Hmm… what errors? You are using `java -jar [jarname.jar]`? I don’t have an M1 Mac, so I unfortunately cannot test.

I guess architecture doesn't matter here. The mod working for you?

**Comment by JJTech0130** [comment]
Looks like you need to use a newer version of Java? What is the output of `java --version`? The JNI part is a little worrying, iirc that means it depends on native code (which is probably for Intel Macs)…

**Comment by JJTech0130** [comment]
> > Hmm… what errors? You are using `java -jar [jarname.jar]`? I don’t have an M1 Mac, so I unfortunately cannot test.
> 
> I guess architecture doesn't matter here. The mod working for you?

I don’t use the chat mod, if that’s what you’re talking about. I don’t even use this version of MultiMC. I just created the methods of running MultiMC on ARM in general (specifically pushed for a compile-time option to use a custom meta repo) (Raspberry Pi) and came across this project by chance 😄.

**Comment by devqcf** [comment]
> > > Hmm… what errors? You are using `java -jar [jarname.jar]`? I don’t have an M1 Mac, so I unfortunately cannot test.
> > 
> > 
> > I guess architecture doesn't matter here. The mod working for you?
> 
> I don’t use the chat mod, if that’s what you’re talking about. I don’t even use this version of MultiMC- I just created the methods of running MultiMC on ARM in general (Raspberry Pi) and came across this project by chance 😄.

Oh, okay 😅

`java -version` prints this:
`openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)`

**Comment by devqcf** [comment]
I managed to execute the jar, I used Zulu-17 jdk. Thanks!

**Comment by devqcf** [comment]
Now while trying to patch the launcher, it throws errors like 
`2021-12-10 21:11:31.190 java[43894:975148] Bad JNI lookup accessibilityHitTest` and it mentions AppKit. I'm gonna try with OpenJDK-17

**Comment by JJTech0130** [comment]
Well, if you’re still having issues, it looks pretty trivial to do without the tool. You have to enter the .app (control-click then “show package contents” or similar), then you should be able to open the info.plist in the text editor, and add a new xml element with the name `NSMicrophoneUsageDescription` and the contents `A Minecraft mod is requesting access to the microphone`. Then run `codesign --deep --remove-signature <your-application>` in the terminal.

**Comment by devqcf** [comment]
> Well, if you’re still having issues, it looks pretty trivial to do without the tool. You have to enter the .app (control-click then “show package contents” or similar), then you should be able to open the info.plist in the text editor, and add a new xml element with the name `NSMicrophoneUsageDescription` and the contents `A Minecraft mod is requesting access to the microphone`. Then run `codesign --deep --remove-signature <your-application>` in the terminal.

It's the same as the patch. After application gets patched after it's signature is removed, I can no longer open it. It says I have no permissions to open an app. I hope the maintainer of repo will get into it and add a permission. I contacted mod discord, they say on multimc it works without any workarounds. This is strange, really

**Comment by JJTech0130** [comment]
Yeah... I'll really don't know at this point... I'll test it if I have time, but no guarantees... could be that it depends on some native library for audio or something that doesn't work on M1

**Comment by ViRb3** [comment]
I did some research on this issue. On macOS, if you run an unsigned binary, it will be executed with all permissions and entitlements granted, just like on Linux. However, if your binary is signed, only the entitlements attached to it will be granted. The way that Simple Voice Chat works around this limitation is that it unsigns (removes all codesigning) of your launcher, effectively forcing it to be executed with all permissions.

Unfortunately, M1 Macs refuse to execute any unsigned code on arm64. Only x64 code via Rosetta2 will still work to preserve compatibility. This means that Simple Voice Chat's method will not work for any arm64 (M1-native) launchers. However, I signed ManyMC with the correct entitlements and everything works as expected. A new build with this fix will be released soon, leaving this issue open until then.

Oh, one more workaround - you can still run any launcher through your Terminal, and the permissions will work, since the launcher will inherit the Terminal's entitlements, and they include almost everything.

**Comment by ViRb3** [comment]
Finally, released in build 5 :)
