### ISSUE TITLE
[Suggestion] Support Modrinth Modpacks Format

### ISSUE THREAD

**Issue by TGMax233Michael** [MinecraftMachina/multimc-macos-arm64#61]
Now **Modrinth** has its own Modpack format, and multimc has supported its modpack format.
It is just another way for players to manually add modpacks with less complications.
I'm also a modpack creator and supporting Modrinth format also benefits modpack creator a lot. :3

**Reference:**
https://github.com/MultiMC/Launcher/issues/3591
https://github.com/MultiMC/Launcher/issues/4699

**Comment by snaco** [comment]
With the Curseforge API not working because of the new authentication requirements, it would be nice to see another modpack source available in the launcher.

**Comment by ViRb3** [comment]
Implemented in Build 10.
