### ISSUE TITLE
Forge not working on Minecraft 1.12.2

### ISSUE THREAD

**Issue by ibll** [MinecraftMachina/multimc-macos-arm64#65]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**
I'm trying to get Forge for 1.12.2, and all Forge versions I've tried greet me with a red X and says the `Patch is not loaded yet.`

Trying to run the game tells me:
```
Instance update failed because: Component metadata update task failed while downloading from remote server:
Job 'Download of meta file net.minecraftforge/14.21.1.2387.json' failed to process:
https://minecraftmachina.github.io/meta-multimc-arm64/net.minecraftforge/14.21.1.2387.json
```

**To reproduce**

1. Go to 'Add Instance'
2. Select Minecraft version `1.12.2`
3. Go to Forge Mod Loader and click on the recommended `14.23.5.2859`, but any of these seem to have problems for me.
4. Press `Ok`, and launch the instance.
5. Oh no, it failed.

**Expected behavior**

The Forge item in the Version tab should show a happy green check mark and the game should start :)

**Logs**

Include ManyMC crash logs.

https://mclo.gs/BZBvESC

**Screenshots**

 ![SCR-20220607-wvw](https://user-images.githubusercontent.com/61601241/172533091-ba2f54c0-0e8f-434b-b85e-e253fb2570ee.png)

**System configuration**

- ManyMC version: [e.g. 0.1.1]
- Java version: [e.g. Azul JDK 8 (1.8.0_332)]

**Additional context**

**Comment by ViRb3** [comment]
Sorry about that, it was an oversight when rebasing the meta. It has now been fixed, please let me know if you still experience it.
