### ISSUE TITLE
Failed to download the assets index

### ISSUE THREAD

**Issue by JDOG787** [MinecraftMachina/multimc-macos-arm64#67]
**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

Whenever I launch the game I get:
```
Instance update failed because: Failed to download the assets index:
Job 'Asset index for fabric-1.18.2' failed to process:
https://launchermeta.mojang.com/v1/packages/de57d9f6d65a980f86df431603287248d4f148b5/1.18.json
```
Other instances do the same but when I restart my mac *sometimes* it fixes it temporarily. 

**To reproduce**

Launch instance

**Expected behavior**

Launch the game rather than crash

**Logs**

```
Instance update failed because: Failed to download the assets index:
Job 'Asset index for fabric-1.18.2' failed to process:
https://launchermeta.mojang.com/v1/packages/de57d9f6d65a980f86df431603287248d4f148b5/1.18.json
```
**System configuration**

- ManyMC version: [e.g. 0.1.1]
- Java version: [e.g. Azul JDK 17 (17.0.3)]

**Comment by ViRb3** [comment]
Sounds like a temporary issue with Mojang's asset store. Can you please try again? Works fine here on Fabric 1.18.2.

**Comment by JDOG787** [comment]
@ViRb3 it does this off and on and is not consistent. It's also not just fabric it's all instances.

**Comment by ViRb3** [comment]
I believe it's a problem with your network as nobody else has ever had this issue. Especially given that it goes on and off... Try on a different internet connection or mobile data to confirm.

**Comment by ViRb3** [comment]
Assuming fixed.

**Comment by JDOG787** [comment]
Yeah, I think it's just my network for some reason, thanks.
