### ISSUE TITLE
Crash When Resolving Mods Id

### ISSUE THREAD

**Issue by TGMax233Michael** [MinecraftMachina/multimc-macos-arm64#68]
**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

Crash  When Resolving Mods ID

**To reproduce**

Start to resolve Mods ID, and then crash.

**Expected behavior**

None

**Logs**

[ManyMC crash logs.](https://pastebin.com/AEf5AgFJ)

**Screenshots**

None

**System configuration**

- ManyMC version: 0.1.1
- Java version: Azul JDK 17 (17.0.3)

**Additional context**

It seems that it is the inability of presenting the mod download link caused crashing.

**Comment by ViRb3** [comment]
Paste is empty.

**Comment by TGMax233Michael** [comment]
https://pastebin.mozilla.org/UFLW6wsH

**Comment by ViRb3** [comment]
From logs:

> QNetworkReply::ContentAccessDenied

Seems like CurseForge API is denying you access to the specific mods. Which modpack is this?

**Comment by ViRb3** [comment]
Actually, I think this is because there's no CurseForge key in that build. Update to build 12 and try again, it will work.
