### ISSUE TITLE
Support for x64/other architectures

### ISSUE THREAD

**Issue by Faboslav** [MinecraftMachina/multimc-macos-arm64#69]
Hello, this is working great for my M1 macbook, but it would be great, if even x64/ or other architectures were detected as well, because right now they are basically non-existing for many-mc.

Why do i need this? I do a lot of testing with fabric/forge and quilt. While Fabric does work just fine, forge does not, so i would like to set for that instance other java in this case java for x64 architecture

**Comment by ViRb3** [comment]
For x64 use PolyMC/MultiMC. This launcher is exclusively M1 native.

**Comment by Faboslav** [comment]
Oh my, but what is the point of using two different launchers then? Life is hard :/

**Comment by ViRb3** [comment]
Eventually PolyMC will support all of ManyMC's features, so you can wait for that I suppose.
