### ISSUE TITLE
"fixup_bundle: not a valid bundle" error when building

### ISSUE THREAD

**Issue by garyteofanus** [MinecraftMachina/multimc-macos-arm64#70]
!! Please fill in this template, DO NOT ignore or delete it. !!

**I tried basic troubleshooting first**

- [x] Carefully read the [installation guide](https://github.com/MinecraftMachina/ManyMC#install)
- [x] Carefully read the [troubleshooting guide](https://github.com/MinecraftMachina/ManyMC#troubleshooting)

**Describe the bug**

While trying to build this project I run into error at fixup_bundle saying that it's not a valid bundle.
 
<img width="1350" alt="Screen Shot 2022-06-15 at 18 22 37" src="https://user-images.githubusercontent.com/40825899/173815796-cf416e83-91b9-4f04-9c46-3e3fe5584035.png">

I think that's the relevant logs, but the complete logs is given down below.

**To reproduce**

1. Install dependencies and xcode cli. 
2. Run `./build.sh`.

**Expected behavior**

Build works successfully

**Logs**
The logs are `[here](https://privatebin.net/?91598d62833a18ee#HshMZ4kzRtJTxz4fe6YWs4GELjHC6Btg5vdVCydLJYtA)`

**Screenshots**
None

**System configuration**

- ManyMC version: latest master (commit 6e4b76b6a5f62e3537792eec0140dafb9cbd3c87)
- Java version: openjdk 18.0.1.1 2022-04-22

**Additional context**
None

**Comment by ViRb3** [comment]
Java 18 is not supported. The build script will usually switch to Java 8 automatically, but that's not working in your case, you probably don't have it installed and/or detectable. Please manually use Java 8 as mentioned in the instructions.

**Comment by garyteofanus** [comment]
Thank you for the response, unfortunately java 8 also doesn't work. I used the same java zulu 8 as in the instructions and it still gives the exact same errors. Do you have any clue why it does that?

**Comment by ViRb3** [comment]
Did you clone this repo's submodules?

**Comment by garyteofanus** [comment]
I did, I used the command `git clone --recurse-submodules https://github.com/MinecraftMachina/ManyMC` to clone this repo.

**Comment by ViRb3** [comment]
Fixed in 75a6e1c823efd5edefbce67a36d9ef1e408a1507.

**Comment by garyteofanus** [comment]
Thank you for the fix, it builds correctly now.
