### ISSUE TITLE
Weird menu bar issue

### ISSUE THREAD

**Issue by sorae42** [MinecraftMachina/multimc-macos-arm64#71]
It keeps showing the same options and options that shouldn't be there.
<img width="323" alt="Screen Shot 2022-07-11 at 03 34 50" src="https://user-images.githubusercontent.com/34794115/178161335-71c0a010-600d-4490-8760-d9efe575339f.png">

**Comment by ViRb3** [comment]
Fixed in https://github.com/PolyMC/PolyMC/issues/695, will be released as part of next update.
