### ISSUE TITLE
Minecraft 1.8.9 crash with forge installed

### ISSUE THREAD

**Issue by Johnnywang2001** [MinecraftMachina/multimc-macos-arm64#75]
I'm trying to run some mods on Minecraft 1.8.9 but the game crashes every time I tries to install forge. Java is up to date and I don't have any other configurations for this instance. I'm not sure if it'll work if I install forge manually but I don't know how to do that with ManyMC. Please help! Thanks!

<img width="770" alt="Screen Shot 2022-07-22 at 2 23 44 PM" src="https://user-images.githubusercontent.com/20619402/180501106-7c6db0f6-a6c4-46b2-8c06-2a01a63d058b.png">
<img width="770" alt="Screen Shot 2022-07-22 at 2 24 24 PM" src="https://user-images.githubusercontent.com/20619402/180501243-ecfa9c6b-3a68-4cbe-b33a-e6deee5c4508.png">

**Comment by Aces-and-Jacks** [comment]
It may be because there's a mod that's not compatible with another mod you have. You can try unchecking a mod and see if it works, and repeat for the other mods if it still doesn't. beyond that I don't know

**Comment by ViRb3** [comment]
Please follow the issue template, it's there for a reason.
- What ManyMC version?
- Your Forge is up-to-date, so it's not that.
- What exact version of Java are you using? You need Java 8 arm64.
- Do you have any mods installed? Try disabling them all and see if it works. If yes, one of your mods is the issue.
