### ISSUE TITLE
[Support Request] ARM Support for Linux devices

### ISSUE THREAD

**Issue by joeyoropesa-dev** [MinecraftMachina/multimc-macos-arm64#78]
Hi developers,

Can you add support for linux devices because linux arm devices don't have Minecraft launcher for arm yet. They have snaps and Pi apps to use but there is no su much support. Mod Loaders don't work property and many devices who use proot to start Linux OS can't use snaps - for example, Termux app.

Many users wants this support because this can help a lot to many people who don't have for example, real PC that can run this game so instead of using PC directly, they can use an alternative to run Minecraft on their slow PC. They can use proot to start linux os and run linux programs via VNC on their slow non-graphics PC devices.

But if they don't have a functional supported Minecraft launcher for arm architecture, this can't be possible.

I don't believe so much that you will accept this support request to allow much more users who can't play that game normally on their device to be able to play with their friends because you will have a lot of work but I hope that you can understand us and make something for us one day.

Thank you so much for your understanding!

**Comment by JJTech0130** [comment]
https://github.com/MinecraftMachina/ManyMC/issues/11

**Comment by ViRb3** [comment]
I truly appreciate your request, but please refer to the issue above.
