### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by SalvadorD75** [MinecraftMachina/multimc-macos-arm64#8]
How is manymc updated is it updated automatically or it has to be deleted and install the new version?  Also, I don't see an update button like multimc which would be good to have

**Comment by ViRb3** [comment]
The ManyMC launcher itself does not have auto-update yet. It is something I plan to add eventually. Currently, if there's a new version of the launcher, you have to download it manually and replace the existing launcher (preserving your data if you want to keep your Minecraft instances).

The Minecraft versions inside ManyMC, however, update automatically. If Mojang released 1.18.2 right now, even without updating the launcher, you will be able to create a new instance with that version.

I hope this answers your questions.
