### ISSUE TITLE
Minecraft 1.5.2 Forge loads with black screen

### ISSUE THREAD

**Issue by LaDerek** [MinecraftMachina/multimc-macos-arm64#80]
Minecraft 1.5.2 Forge loads with black screen

1. Run Minecraft 1.5.2 with latest forge
2. See error

**Logs**

https://mclo.gs/f8LWxhf

**Screenshots**

![image](https://user-images.githubusercontent.com/82894246/184260131-d979db72-8ae0-4b03-9f8f-6937aab3787f.png)

**System configuration**

- ManyMC version: 0.1.2 develop
- Java version: 312 bell soft idk

**Comment by ViRb3** [comment]
Something is very broken with your instance given the logs:
> java.lang.NoClassDefFoundError: net/minecraft/block/Block

Anyway, I can't run Minecraft 1.5.2 with Forge either. It appears that Forge is written for Java 6, while two of our "fixed" libraries are written for Java 8: 
- java-objc-bridge-1.1.0-mmachina.1.jar
- text2speech-1.11.3.jar

Would need to re-compile them i suppose. Minecraft 1.5.2 has color and stuttering issues as well, so I wouldn't say it's very usable anyway.

**Comment by tobiasvanslingerland** [comment]
Same issue on 1.4.7 when starting FTB Ultimate
https://mclo.gs/ANFR71N
Hopefully this gets fixed at some point!
FTB Ultimate is my favourite pack
