### ISSUE TITLE
Some mods can cause the player to be invisible, especially on servers

### ISSUE THREAD

**Issue by christopherlewisghs** [MinecraftMachina/multimc-macos-arm64#81]
When using certain mods (like Wynntils) on 1.12.2 forge, teleporting constantly or dying can cause the player to be invisible, and will remain that way until the player leaves the lobby.

**Comment by ViRb3** [comment]
Unless you can confirm that this happens on ManyMC and not on x64 Minecraft, I can almost guarantee that the problem is not with ManyMC.
