### ISSUE TITLE
Shaders broken on M1

### ISSUE THREAD

**Issue by Bexin3** [MinecraftMachina/multimc-macos-arm64#82]
**Describe the bug**

So this isn't a ManyMC specific issue, however on 1.12.2 shaders on M1 are very broken and even on 1.18 there are weird artefacts, BSL shaders also have a broken font. On 1.12.2 shaders however sometimes lock game to very low fps and don't use full performance - 10 percent of the times I get 50fps, while 90 I get 4 fps and the MacBook doesn't get hot at all. Also looking through leaves blocks beyond don't render. Also seus v10 shaders work on normal MacBooks after a fix but not on M1

**To reproduce**

1. Install 1.12.22.
2. Install optifine
3. add shaders
4. look through leaves or launch multiple times

**Screenshots**

-BSL when its low fps + leaves issues
![Screenshot 2022-08-24 at 10 00 32](https://user-images.githubusercontent.com/88098139/186364167-e39eb26b-2ca7-4bcd-a5d7-795e487dba96.jpeg)
-SEUS v10 that would work on not M1
<img width="1728" alt="Screenshot 2022-08-24 at 10 02 57" src="https://user-images.githubusercontent.com/88098139/186364499-c90da4f0-c724-4c59-841f-342b5acae08b.png">

**System configuration**

- ManyMC version: 0.1.2
- Java version: [e.g. Azul JDK 8)]
- M1 Pro

**Comment by ViRb3** [comment]
Yep, thank apple's OpenGL implementation for this. There's nothing straightforward we can do, some people are working on a better OpenGL but that will take time. Feel free to ask on discord for more info on working shaders and OpenGL status.
